using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace QuadLibrary
{
    public class Square : Quadrilateral, Points
    {
        public int Width { get; set; }
        public int x1 { get; set; }
        public int y1 { get; set; }
        public int x2 { get; set; }
        public int y2 { get; set; }
        public int x3 { get; set; }
        public int x4 { get; set; }
        public int y3 { get; set; }
        public int y4 { get; set; }

        public Square(int X1, int Y1, int Y2)
        {
            Name = "Square";
            Width = (Y2 - Y1);
            // these are being entered by the user
            x1 = X1;
            y1 = Y1;
            y2 = Y2;
            // these are generated by the program based on the user input
            x2 = X1;
            x3 = X1 + x2;
            y3 = Y1;
            x4 = x3;
            y4 = y2;
        }

        public override int Area()
        {
            return Convert.ToInt32(Math.Pow(Width, 2));
        }

        public override int Perimeter()
        {
            return 4 * Width;
        }

        public override void GetInfo()
        {
            base.GetInfo();
            Console.WriteLine($"It has an area of {Width}");
        }
    }
}
